output_dir: structure_processed
actions:
  - name: "tempo_change_structured"
    steps:
      - step: 1
        selection_type: "random"
        operation: "tempo_change"
        parameters:
          tempo_change_len_range: [2, 4]
          tempo_change_range: [0.1, 8.0]
          modifications:
            - percentage: 10
              save_suffix: "_tempo1_1_step1_nt10"
            - percentage: 30
              save_suffix: "_tempo1_1_step1_nt30"
            - percentage: 50
              save_suffix: "_tempo1_1_step1_nt50"
            - percentage: 80
              save_suffix: "_tempo1_1_step1_nt80"