output_dir: velocity_processed
actions:
  - name: "notes_velocity_change"
    steps:
      - step: 1
        selection_type: "random"
        operation: "velocity_change"
        parameters:
          source_velocities: []
          target_velocity:
          modifications:
            - percentage: 10
              save_suffix: "_velocity1_1_step1_nt10"
            - percentage: 30
              save_suffix: "_velocity1_1_step1_nt30"
            - percentage: 50
              save_suffix: "_velocity1_1_step1_nt50"
            - percentage: 80
              save_suffix: "_velocity1_1_step1_nt80"